### ISSUE TITLE
Reset password doesn't work, wrong template

### ISSUE THREAD

**Issue by Mark-H** [modmore/CommerceTheme_Red#6]
> In red template, the reset password doesn't work.
> Why : The reset password resource has the same template that forgot password resource.
> You must add a new template reset password and inside put
> ```[[!ResetPassword? &loginResourceId=`[[++commerce.login_resource]]`]]```

https://secure.helpscout.net/conversation/1183630372/23022?folderId=46279

**Comment by muzzwood** [comment]
Fixed in commit [eb8a679c](https://github.com/modmore/CommerceTheme_Red/commit/eb8a679c5c4f0b68818741c1b5c67dbef652fe64)
